# Optional Ollama service - run this separately if you want Ollama on the same server
# Usage: docker-compose -f docker-compose.ollama.yml up -d

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    command: serve
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      # Optional: Pre-pull specific models on startup
      # - OLLAMA_MODELS=gemma3:4b,llama2

volumes:
  ollama-data:
    driver: local