services:
  evergabe-scraper:
    build: .
    container_name: evergabe-scraper
    ports:
      - "5005:5005"
    volumes:
      # Mount output directory for results
      - ./output:/app/output
      # Mount config files
      - ./config.yaml:/app/config.yaml:ro
      - ./settings.json:/app/settings.json
      # Mount .env file for credentials
      - ./.env:/app/.env:ro
      # Optional: Mount templates and static for development
      - ./templates:/app/templates
      - ./static:/app/static
    environment:
      # Force headless mode in container
      - HEADLESS=true
      - DISPLAY=:99
      # Chrome flags for container environment
      - CHROME_FLAGS=--no-sandbox --disable-dev-shm-usage --disable-gpu --headless --disable-blink-features=AutomationControlled
      # Optional: External Ollama server URL (change IP as needed)
      # - OLLAMA_URL=http://192.168.1.100:11434
    restart: unless-stopped
    # Increase shared memory for Chrome
    shm_size: '2gb'
    # Security options for Chrome
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN